FROM nginx
MAINTAINER venkat venkata.ch17@gmail.com
RUN apt-get update
COPY index.html /usr/share/nginx/html/index.html
COPY start_all.sh /usr/local/start_all.sh
CMD ["/usr/local/start_all.sh"]
EXPOSE 8080
