FROM ubuntu:16.04
RUN apt-get update 
RUN apt-get install apache2 -y 
RUN apt-get install apache2-utils -y 
RUN apt-get clean 
COPY index.html /var/www/html/index.html
COPY start_all.sh /usr/local/start_all.sh
ENTRYPOINT service apache2 restart && bash
EXPOSE 80 
CMD ["apache2ctl", "-D", "FOREGROUND"]
CMD ["/usr/local/start_all.sh"]
